### ISSUE TITLE
Modifying helicopters still make them "unflyable" 

### ISSUE THREAD

**Issue by Torres84f** [SpadeDraco/useful_helicopters#1]
I took a small flyer and tried removing the box to add a trunk for more space but it won't let me without breaking the flyability.

**IN THIS REPORT I HAD ALREADY REMOVED YOUR MOD FROM THE MOD LIST** that's why the report doesn't show the useful helicopters mod loaded, but for testing I loaded it and tried with it enabled, in this current save I just wanted the report so I had to disable it that's why it's not showing in this list

17:27:05.194 :  GAME REPORT:
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-7071-g00daf3a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Mining Mod [Mining_Mod],
    Caches [P_Caches],
    Blaze Industries [blazeindustries],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod [crt_expansion],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Aftershock [aftershock],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Dorf Life [Dorf_Life],
    Dorf Life - UndeadPeople Tileset [Dorf_LifeUDP],
    DinoMod [DinoMod],
    DinoMod - UndeadPeople Tileset [DinoModUDP],
    Magiclysm [magiclysm],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP]

**Comment by SpadeDraco** [comment]
This was caused by a change in how the game handles simple rotors. Mod is being rebuilt from the ground up for 0.F and this should no longer be a problem.
